pipeline {
  agent any
    stages {
		stage('Setup: Rotate slice DBs'){
			steps{
				script{
					dir('updateStableIds'){
						withCredentials([usernamePassword(credentialsId: 'mySQLUsernamePassword', passwordVariable: 'pass', usernameVariable: 'user')]){
							sh "mysql -u$user -p$pass -e \'drop database if exists slice_previous; create database slice_previous\'"
							sh "zcat  test_slice_69_snapshot.dump.gz 2>&1 | mysql -u$user -p$pass -hlocalhost slice_previous"
							sh "mysqldump -u$user -p$pass slice_test > test_slice_70_snapshot.dump"
							sh "gzip -f test_slice_70_snapshot.dump"
							sh "mysql -u$user -p$pass -e \'drop database if exists slice_current; create database slice_current\'"
							sh "zcat  test_slice_70_snapshot.dump.gz 2>&1 | mysql -u$user -p$pass -hlocalhost slice_current"
						}
					}
				}
			}
		}
	    stage('Setup: Back up gk_central'){
		    steps{
			    script{
				    dir('updateStableIds'){
					    withCredentials([usernamePassword(credentialsId: 'mySQLUsernamePassword', passwordVariable: 'pass', usernameVariable: 'user')]){
							sh "mysqldump -u$user -p$pass gk_central > gk_central_70_before_st_id.dump"
							sh "gzip -f gk_central_70_before_st_id.dump"
						}
					}
				}
			}
		}			    
		stage('Setup: Build jar file'){
			steps{
				script{
					dir('updateStableIds'){
						sh "mvn clean compile assembly:single"
					}
				}
			}
		}
		stage('Main: Update Stable Identifiers'){
			steps {
				script{
					dir('updateStableIds'){
						withCredentials([file(credentialsId: 'Config', variable: 'FILE')]){
							sh "java -jar target/updateStableIds-0.0.1-SNAPSHOT-jar-with-dependencies.jar $FILE"
						}
					}
				}
			}
		}
    }
}
