pipeline {
  agent any
    stages {
        stage('Build') {
            steps {
              dir('release-common-lib') {
                sh 'mvn clean install'
              }


              dir('updateStableIds') {
                sh 'pwd'
    	          sh 'mvn clean compile assembly:single'
                withCredentials([file(credentialsId: 'UpdateStableIdsConfig', variable: 'configFile')]) {
                  sh "cat \$configFile"
                }


              }
           }
        }
    }
}
