pipeline {
  agent any
    stages {
        stage('Build') {
            steps {
            dir('updateStableIds') {
    	         sh 'mvn clean compile assembly:single'
               sh 'cat src/main/resources/config.properties'
                }
            }
        }
    }
}
